#pragma once

#include "drape/dynamic_texture.hpp"
#include "drape/texture.hpp"

#include "coding/reader.hpp"

#include "geometry/rect2d.hpp"

#include <cstdint>
#include <map>
#include <memory>
#include <mutex>
#include <set>
#include <string>
#include <string_view>
#include <unordered_map>
#include <utility>
#include <vector>

namespace grove
{
// Brand logo badges for places of chains (Albert Heijn, McDonald's, Shell...), generated by
// tools/grove/brand_logos.py into data/grove_brands.txt (index) and data/grove_brands.bin (PNGs).
// A badge is a symbol named "brand:<Wikidata id>": TextureManager::GetSymbolRegionSafe hands such names to
// BrandTexture, which loads each badge on first use into a slot of one dynamic texture.
std::string_view constexpr kBrandSymbolPrefix = "brand:";

// Overlay priority of logos: above every map label and icon (dp::CalculateOverlayPriority: 0xFF, then a depth below
// 2^15, rank and 0xFFFF), below the user marks shown at every zoom. Logos are pinned: nothing on the map hides them,
// and they never hide each other (OverlayTree).
uint64_t constexpr kBrandPriority = 0xFF00FFFFFFFFFFFF;

// Badge size on screen: a little larger than the category icons, so logos stay recognisable.
double constexpr kBrandBadgeDp = 32.0;

class BrandPack
{
public:
  static BrandPack const & Instance();

  // Whether some brand is called this (a quick test before gathering the place's types for Find).
  bool HasName(std::string_view name) const;

  // Wikidata id of the brand with this name, in this Organic Maps country (e.g. "Netherlands") and one of these
  // place types (e.g. "shop-supermarket"), or empty.
  std::string_view Find(std::string_view name, std::string_view country,
                        std::vector<std::string> const & placeTypes) const;

  // Popularity rank: 0 for the brand with the most places, larger for rarer ones and unknown brands.
  size_t GetRank(std::string_view qid) const;

  // Changes whenever the pack does, for caches built from it.
  uint64_t GetSignature() const { return m_signature; }

  // The logo's main colour (0xRRGGBB), or 0 for grey logos and unknown brands.
  uint32_t GetColor(std::string_view qid) const;

  // The badge PNG, or empty if the brand is unknown.
  std::vector<uint8_t> ReadBadge(std::string_view qid) const;

private:
  BrandPack();

  struct Brand
  {
    std::string m_qid;
    uint64_t m_offset = 0;
    uint32_t m_size = 0;
    std::vector<std::string> m_countries;  // Empty: anywhere.
    std::vector<std::string> m_types;
    uint32_t m_color = 0;
  };

  std::vector<Brand> m_brands;                                    // Most used first.
  std::unordered_map<std::string, std::vector<size_t>> m_byName;  // Lower-case name -> brands.
  std::unordered_map<std::string, size_t> m_byQid;
  std::unique_ptr<ModelReader> m_pack;
  uint64_t m_signature = 14695981039346656037ULL;
};

class BrandKey : public dp::Texture::Key
{
public:
  explicit BrandKey(std::string qid) : m_qid(std::move(qid)) {}
  dp::Texture::ResourceType GetType() const override { return dp::Texture::ResourceType::Symbol; }
  bool operator<(BrandKey const & other) const { return m_qid < other.m_qid; }

  std::string m_qid;
};

class BrandResourceInfo : public dp::Texture::ResourceInfo
{
public:
  using dp::Texture::ResourceInfo::ResourceInfo;
  dp::Texture::ResourceType GetType() const override { return dp::Texture::ResourceType::Symbol; }
};

// Fixed-size slots in a grid. When all slots are taken, further brands keep their category icons.
class BrandIndex
{
public:
  BrandIndex(m2::PointU const & textureSize, uint32_t slotSize);

  // Reserves a slot and loads the badge. False if the brand is unknown, its badge is broken or no slot is left.
  bool Prepare(std::string const & qid);

  ref_ptr<dp::Texture::ResourceInfo> MapResource(BrandKey const & key, bool & newResource);
  void UploadResources(ref_ptr<dp::GraphicsContext> context, ref_ptr<dp::Texture> texture);

private:
  struct Pending
  {
    m2::RectU m_rect;
    std::vector<uint8_t> m_pixels;
  };

  m2::PointU const m_textureSize;
  uint32_t const m_slotSize;
  uint32_t m_nextSlot = 0;
  std::map<std::string, BrandResourceInfo, std::less<>> m_mapping;
  std::set<std::string, std::less<>> m_failed;
  std::vector<Pending> m_pending;
  std::mutex m_mutex;
};

class BrandTexture : public dp::DynamicTexture<BrandIndex, BrandKey, dp::Texture::ResourceType::Symbol>
{
  using Base = dp::DynamicTexture<BrandIndex, BrandKey, dp::Texture::ResourceType::Symbol>;

public:
  BrandTexture(ref_ptr<dp::HWTextureAllocator> allocator, double visualScale);
  ~BrandTexture() override { Base::Reset(); }

  bool Prepare(std::string const & qid) { return m_index.Prepare(qid); }

private:
  BrandIndex m_index;
};

// The Wikidata id in a brand symbol name, or empty for other symbols.
inline std::string_view BrandQid(std::string_view symbolName)
{
  return symbolName.starts_with(kBrandSymbolPrefix) ? symbolName.substr(kBrandSymbolPrefix.size()) : std::string_view{};
}
}  // namespace grove
