#!/usr/bin/env python3
"""Writes the modules' index from the registry (modules/core/platform/features.cpp), the hooks in upstream files
(check_hooks.py) and the files in each module:
- modules/README.md, the overview;
- the generated part of each modules/<module>/README.md (the rest of the file is kept);
- data/grove_modules.txt, which the app shows for each switch.
Run it after adding a module or a hook; CI checks that the index is up to date.

    modules/core/tools/generate_index.py [--check]
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
import check_hooks  # noqa: E402

ROOT = check_hooks.ROOT
MODULES = os.path.join(ROOT, "modules")
APP_INDEX = os.path.join(ROOT, "data", "grove_modules.txt")
BEGIN = "<!-- Generated by modules/core/tools/generate_index.py; edit the registry or the hooks, not these lines. -->"
END = "<!-- End of the generated part. -->"
CORE_ABOUT = (
    "What every module stands on: the registry of switches and Stock (platform/features.hpp), the raster layers "
    "relief and land cover draw with, the build hook that compiles modules into upstream's libraries "
    "(modules.cmake), and the tools: hook check, this index, renders, upstream sync, the emulator test."
)


def registry():
    """([(module, group, icon, key, default, restart, about)] in the registry's order, {group: icon})."""
    text = open(os.path.join(MODULES, "core", "platform", "features.cpp"), encoding="utf-8").read()
    entries = []
    pattern = (r'\{\w+, G::(\w+), "([a-z0-9_]+)", "([^"]+)", "(\w+)", (true|false), (true|false),'
               r'\s*((?:"(?:[^"\\]|\\.)*"\s*)+)')
    for group, module, icon, key, default, restart, about in re.findall(pattern, text):
        about = "".join(re.findall(r'"((?:[^"\\]|\\.)*)"', about)).replace('\\"', '"')
        entries.append((module, group, icon, key, default == "true", restart == "true", about))
    groups = dict(re.findall(r'\{"(\w+)", "([^"]+)"\}', text[text.index("kGroups[]"):]))
    return entries, groups


def title(module):
    return module.replace("_", " ").capitalize().replace("Poi ", "POI ").replace(" 3d", " 3D").replace(" 11", " 11")


def own_files(module):
    files = []
    for dirpath, dirnames, filenames in os.walk(os.path.join(MODULES, module)):
        dirnames[:] = sorted(d for d in dirnames if d not in ("ideas", "__pycache__"))
        for f in sorted(filenames):
            rel = os.path.relpath(os.path.join(dirpath, f), os.path.join(MODULES, module))
            if rel != "README.md":
                files.append(rel)
    return files


def hook_files():
    """{module: {upstream file: hook count}}."""
    base = open(check_hooks.BASE_FILE).read().strip()
    features = check_hooks.feature_modules()
    result = {}
    for path in check_hooks.changed_files(base):
        if check_hooks.SKIP.match(path):
            continue
        lines = open(os.path.join(ROOT, path), encoding="utf-8", errors="replace").read().split("\n")
        for start, count, _ in check_hooks.hunks(base, path):
            first = max(start - 1, 0)
            window = lines[max(first - check_hooks.MARKER_REACH, 0) : first + max(count, 1) + check_hooks.MARKER_REACH]
            for module in dict.fromkeys(m for l in window for m in check_hooks.named_modules(l, features)):
                counts = result.setdefault(module, {})
                counts[path] = counts.get(path, 0) + 1
    return result


def module_block(module, info, hooks):
    lines = [BEGIN, ""]
    if info:
        _, group, icon, key, default, restart, about = info
        lines += [f"{icon} {about}", ""]
        lines += [f"Switch `{key}`, {'on' if default else 'off'} by default, "
                  f"{'after a restart' if restart else 'at once'}. Off, or with Stock on, upstream's code runs.", ""]
    else:
        lines += [f"⚙ {CORE_ABOUT}", ""]
    if hooks:
        lines.append("Hooks in upstream files:")
        lines += [f"- `{path}`" + (f" ({n})" if n > 1 else "") for path, n in sorted(hooks.items())]
        lines.append("")
    files = own_files(module)
    if files:
        lines.append("Files:")
        lines += [f"- `{f}`" for f in files]
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def readme(module, info, hooks):
    path = os.path.join(MODULES, module, "README.md")
    block = module_block(module, info, hooks)
    if os.path.exists(path):
        text = open(path, encoding="utf-8").read()
        if BEGIN in text and END in text:
            return path, text[: text.index(BEGIN)] + block + text[text.index(END) + len(END) :]
        return path, text.rstrip() + "\n\n" + block + "\n"
    return path, f"# {title(module)}\n\n{block}\n\nIdeas that build on this module go in `ideas/`.\n"


def overview(entries, groups, hooks):
    lines = [
        "# Grove's modules",
        "",
        "Grove is Organic Maps with modules. Each module is one change, in its own folder, behind its own switch; with",
        "Stock on, or every switch off, only Organic Maps' code runs. An upstream file only gets small hooks, each naming",
        "its module (`modules/core/tools/check_hooks.py` checks them). New feature ideas go in `ideas/`, ideas for an",
        "existing module in its own `ideas/`.",
        "",
        BEGIN,
        "",
        "| | Module | What it does | Switch | Hooks |",
        "| --- | --- | --- | --- | --- |",
        f"| ⚙ | [core](core/) | The registry, Stock, the build hook and the tools. | | "
        f"{sum(hooks.get('core', {}).values())} |",
    ]
    last = None
    for module, group, icon, key, default, restart, about in entries:
        if group != last:
            lines.append(f"| {groups[group]} | **{group}** | | | |")
            last = group
        switch = f"{'on' if default else 'off'}{', restart' if restart else ''}"
        lines.append(f"| {icon} | [{module}]({module}/) | {about} | {switch} | "
                     f"{sum(hooks.get(module, {}).values())} |")
    lines += ["", END, ""]
    return "\n".join(lines)


def app_index(entries, hooks):
    lines = ["# Grove's modules for the app's settings, generated by modules/core/tools/generate_index.py.",
             "# module<TAB>upstream files with hooks (;)<TAB>the module's own files (;)"]
    for module in ["core"] + [e[0] for e in entries]:
        lines.append(f"{module}\t{';'.join(sorted(hooks.get(module, {})))}\t{';'.join(own_files(module))}")
    return "\n".join(lines) + "\n"


def main():
    entries, groups = registry()
    hooks = hook_files()
    outputs = [(os.path.join(MODULES, "README.md"), overview(entries, groups, hooks)),
               (APP_INDEX, app_index(entries, hooks))]
    infos = {e[0]: e for e in entries}
    for module in ["core"] + list(infos):
        os.makedirs(os.path.join(MODULES, module), exist_ok=True)
        outputs.append(readme(module, infos.get(module), hooks.get(module, {})))
    stale = []
    for path, text in outputs:
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old == text:
            continue
        stale.append(os.path.relpath(path, ROOT))
        if "--check" not in sys.argv:
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
    if "--check" in sys.argv and stale:
        print("The modules' index is out of date, run modules/core/tools/generate_index.py:", *stale, sep="\n  ")
        return 1
    print(f"{len(entries)} modules and core; {'updated ' + str(len(stale)) + ' files' if stale else 'up to date'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
