#pragma once

#include "drape_frontend/map_shape.hpp"
#include "drape_frontend/render_state_extension.hpp"
#include "drape_frontend/shape_view_params.hpp"

#include "shaders/programs.hpp"

#include "drape/attribute_provider.hpp"
#include "drape/batcher.hpp"
#include "drape/texture_manager.hpp"
#include "drape/utils/vertex_decl.hpp"

#include "indexer/drawing_rule_def.hpp"

#include <array>
#include <string>
#include <utility>

namespace grove
{
// Apple Maps-style place dots. A place icon gets a small dot of its category color under it: symbol
// "<icon>-dot", generated by modules/look/tools/generate_symbols.py. The dot is drawn in the geometry layer, above
// all areas and roads, and has no overlay handle, so it never takes part in collisions: a visible icon covers
// its own dot, and when the icon is displaced by a neighbour the dot stays.
class PoiDotShape : public df::MapShape
{
public:
  PoiDotShape(m2::PointD const & mercatorPt, m2::PointD const & tileCenter, float posZ, std::string dotName)
    : m_pt(mercatorPt)
    , m_tileCenter(tileCenter)
    , m_posZ(posZ)
    , m_dotName(std::move(dotName))
  {}

  void Draw(ref_ptr<dp::GraphicsContext> context, ref_ptr<dp::Batcher> batcher,
            ref_ptr<dp::TextureManager> textures) const override
  {
    dp::TextureManager::SymbolRegion region;
    textures->GetSymbolRegion(m_dotName, region);

    // Above every area and line of the geometry layer; overlays are drawn later, on top.
    float constexpr kDepth = static_cast<float>(drule::kMaxLayeredDepthFg);
    glsl::vec2 const pt = glsl::ToVec2(ConvertToLocal(m_pt, m_tileCenter, df::kShapeCoordScalar));
    glsl::vec4 const position(pt, kDepth, -m_posZ);
    m2::PointF const half = region.GetPixelSize() * 0.5f;
    m2::RectF const & tex = region.GetTexRect();

    using SV = gpu::SolidTexturingVertex;
    std::array<SV, 4> vertexes = {SV(position, glsl::vec2(-half.x, half.y), glsl::vec2(tex.minX(), tex.maxY())),
                                  SV(position, glsl::vec2(-half.x, -half.y), glsl::vec2(tex.minX(), tex.minY())),
                                  SV(position, glsl::vec2(half.x, half.y), glsl::vec2(tex.maxX(), tex.maxY())),
                                  SV(position, glsl::vec2(half.x, -half.y), glsl::vec2(tex.maxX(), tex.minY()))};

    auto state = df::CreateRenderState(gpu::Program::Texturing, df::DepthLayer::GeometryLayer);
    state.SetProgram3d(gpu::Program::TexturingBillboard);
    state.SetDepthTestEnabled(true);
    state.SetColorTexture(region.GetTexture());
    state.SetTextureFilter(dp::TextureFilter::Nearest);
    state.SetTextureIndex(region.GetTextureIndex());

    dp::AttributeProvider provider(1 /* streamCount */, static_cast<uint32_t>(vertexes.size()));
    provider.InitStream(0 /* streamIndex */, SV::GetBindingInfo(), make_ref(vertexes.data()));
    batcher->InsertTriangleStrip(context, state, make_ref(&provider));
  }

private:
  m2::PointD const m_pt;
  m2::PointD const m_tileCenter;
  float const m_posZ;
  std::string const m_dotName;
};

// Adds the dot for a place icon, if the icon has one.
template <typename InsertShapeFn>
void InsertPoiDot(InsertShapeFn const & insertShape, ref_ptr<dp::TextureManager> textures,
                  m2::PointD const & mercatorPt, df::PoiSymbolViewParams const & iconParams,
                  std::string const & categoryIcon)
{
  std::string dotName = categoryIcon + "-dot";
  dp::TextureManager::SymbolRegion region;
  if (textures->GetSymbolRegionSafe(dotName, region))
    insertShape(
        make_unique_dp<PoiDotShape>(mercatorPt, iconParams.m_tileCenter, iconParams.m_posZ, std::move(dotName)));
}
}  // namespace grove
