#!/usr/bin/env python3
"""Builds Grove's bundled pack of Mangrove reviews, so place cards show them offline.

    tools/grove/mangrove_reviews.py [--workers 8]

Mangrove (https://mangrove.reviews) is an open review commons (CC BY 4.0). This asks its API for every review of a
place with a geo subject ("geo:52.3562,4.9115?q=Veganees&u=50"), 10-degree box by box, splitting boxes whose answer
is too large, and packs them by 1-degree cell: data/grove_reviews.bin holds a zlib-compressed block per cell and
data/grove_reviews.txt is the index. libs/map/grove_reviews.cpp reads the cells around a place and adds the newest
reviews from the API when online. Rebuild before a release to refresh it.
"""

import argparse
import concurrent.futures
import json
import math
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import zlib

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
API = "https://api.mangrove.reviews/geo"
STEP = 10


def fetch(box):
    xmin, ymin, xmax, ymax = box
    url = f"{API}?xmin={xmin}&ymin={ymin}&xmax={xmax}&ymax={ymax}"
    for attempt in range(8):
        try:
            with urllib.request.urlopen(url, timeout=120) as response:
                return json.load(response)["reviews"]
        except urllib.error.HTTPError as e:
            if e.code == 413:  # Too many reviews for one answer: split the box.
                return None
            if attempt == 7:
                raise
        except Exception:  # noqa: BLE001 -- retried, then raised
            if attempt == 7:
                raise
        print(f"retry {url}", file=sys.stderr)
        time.sleep(2 ** attempt)  # The API allows only a few requests a second.


def fetch_box(box):
    reviews = fetch(box)
    if reviews is not None:
        return reviews
    xmin, ymin, xmax, ymax = box
    xmid, ymid = (xmin + xmax) / 2, (ymin + ymax) / 2
    result = []
    for sub in ((xmin, ymin, xmid, ymid), (xmid, ymin, xmax, ymid), (xmin, ymid, xmid, ymax), (xmid, ymid, xmax, ymax)):
        result += fetch_box(sub)
    return result


def escape(text):
    return text.replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n").replace("\r", "")


def parse_subject(sub):
    """(lat, lon, uncertainty, name) of a geo subject, or None."""
    if not sub.startswith("geo:"):
        return None
    point, _, query = sub[4:].partition("?")
    try:
        lat, lon = (float(v) for v in point.split(",")[:2])
    except ValueError:
        return None
    params = urllib.parse.parse_qs(query)
    try:
        uncertainty = int(float(params.get("u", ["0"])[0]))
    except ValueError:
        uncertainty = 0
    return lat, lon, uncertainty, params.get("q", [""])[0]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--workers", type=int, default=2)
    args = parser.parse_args()

    boxes = [(x, y, x + STEP, y + STEP) for x in range(-180, 180, STEP) for y in range(-90, 90, STEP)]
    reviews = {}
    with concurrent.futures.ThreadPoolExecutor(args.workers) as pool:
        for done, found in enumerate(pool.map(fetch_box, boxes), 1):
            for r in found:
                reviews[r["signature"]] = r["payload"]
            if done % 100 == 0:
                print(f"boxes: {done}/{len(boxes)}, reviews: {len(reviews)}", file=sys.stderr)

    cells = {}
    for payload in reviews.values():
        subject = parse_subject(payload.get("sub", ""))
        if not subject:
            continue
        lat, lon, uncertainty, name = subject
        rating = payload.get("rating")
        rating = 0 if rating is None else max(0, min(100, int(rating)))
        author = (payload.get("metadata") or {}).get("nickname") or ""
        line = "\t".join([f"{lat:.7f}", f"{lon:.7f}", str(uncertainty), escape(name), str(rating),
                          str(int(payload.get("iat", 0))), escape(author), escape(payload.get("opinion") or "")])
        cells.setdefault((math.floor(lat), math.floor(lon)), []).append(line)

    index = ["# Grove's Mangrove reviews (CC BY 4.0), generated by tools/grove/mangrove_reviews.py. Do not edit.",
             "# lat<TAB>lon<TAB>offset<TAB>size of each 1-degree cell's zlib block of review lines:",
             "# lat lon uncertainty name rating(0..100) time author opinion, with \\t \\n \\\\ escaped"]
    with open(os.path.join(ROOT, "data", "grove_reviews.bin"), "wb") as pack:
        for (lat, lon), lines in sorted(cells.items()):
            block = zlib.compress("\n".join(sorted(lines)).encode(), 9)
            index.append(f"{lat}\t{lon}\t{pack.tell()}\t{len(block)}")
            pack.write(block)
    with open(os.path.join(ROOT, "data", "grove_reviews.txt"), "w") as f:
        f.write("\n".join(index) + "\n")
    print(f"packed {sum(len(v) for v in cells.values())} reviews in {len(cells)} cells", file=sys.stderr)


if __name__ == "__main__":
    main()
